# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nokia/msm8937-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter PLE D1C,$(TARGET_DEVICE)),)

endif
